### ISSUE TITLE
编译一个安卓的版本

### ISSUE THREAD

**Issue by JackyLucifer** [MouseChannel/MCGS#1]
问以下，可否编一个安卓的版本，MCRT有安卓的demo
现在你这个没有安卓的部分
能不能弄个

万分感谢

**Comment by MouseChannel** [comment]
最经在秋招暂时没空，后续会支持的

**Comment by MouseChannel** [comment]
> 问以下，可否编一个安卓的版本，MCRT有安卓的demo 现在你这个没有安卓的部分 能不能弄个
> 
> 万分感谢

最经在秋招暂时没空，后续会支持的

**Comment by brisyramshere** [comment]
同求，非常感谢

**Comment by MouseChannel** [comment]
> 同求，非常感谢

最经在秋招暂时没空，后续会支持的
不过可能会先优化一波，比如LightGaussian那些压缩的方法
